package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.LoanInfo;
import com.bjpowernode.p2p.model.vo.PaginationVO;

import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {


     List<LoanInfo> selectLoanInfoByProductStatus(Integer productStatus) ;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int updateByPrimaryKey(LoanInfo record);

    Double selectHistoryAverageRate();

//    根据产品类型查询产品信息列表
    List<LoanInfo> selectLoanInfoListByProductType(Map<String, Object> paramMap);

//    根据产品类型查询产品数量
    Long selectTotalLoanInfo(Map<String, Object> paramMap);

    int updateLeftProductMoneyByLoanId(Map<String, Object> paramMap);
}