package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.RechargeRecord;

import java.util.List;
import java.util.Map;

public interface RechargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int insert(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int insertSelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    RechargeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int updateByPrimaryKeySelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbggenerated Tue Jun 11 18:06:15 CST 2019
     */
    int updateByPrimaryKey(RechargeRecord record);

    List<RechargeRecord> selectRecentRechargeRecordListByUid(Map<String, Object> paramMap);

    int updateRechargeRecordByRechargeNo(RechargeRecord rechargeRecord);

    RechargeRecord selectRechargeRecordByRechardNo(String out_trade_no);

    List<RechargeRecord> selectRechargeRecordByStatus(Integer rechargeStatus);
}